### PR TITLE
fix: update vue component version for release

### PR DESCRIPTION
**Pull request by miaulightouch**
It's time for release this vue component, we have to change its version first.

it requires package owner's help.

### CODE REVIEW

**Comment by SangwonOh** [comment]
@miaulightouch Thank you for your nice job!

**Comment by miaulightouch** [comment]
@SangwonOh Can you please release new vue component on npm? I don't have right to do.

**Comment by SangwonOh** [comment]
Thanks for the reminder 😄  Publish completed!

**Comment by miaulightouch** [comment]
Thank you!

**Pull request merged**
