### PR TITLE
feat: seek back/forward 10s on double tap

### PR DESCRIPTION
**Pull request by hernanrz**
My implementation for #371 , looking forward to your feedback, thanks!

### CODE REVIEW

**Comment by dygy** [comment]
are you sure it should be enabled by default?  I guess it's good feature to be enablable

**Comment by hernanrz** [comment]
That's a good point, it can be made into an opt-in feature, I'll update the branch later today

**Comment by dygy** [comment]
i just imagined my stakeholders to say they don't want this feature :DDDD

**Review by SangwonOh — CHANGES_REQUESTED** [review]
@hernanrz I'll wait for you to change this feature to enable it as an option. Thank you very much for your contribution 👍

**Review by dygy — APPROVED** [review]

**Review by SangwonOh — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
