### PR TITLE
Hls.js as part of OvenPlayer

### PR DESCRIPTION
**Pull request by dygy**
As a user of OvenPlayer, I had to use OvenPlayer with HLS. There are mentions that Ovenplayers asks for HLS js, but how it uses it isn't nice.

EXP. of Next JS app-router users of OvenPlayer in code looks like this.
image
So even if their code doesn't look like this :D anyway - if OvenPlayer cannot yet do HLS without Hls.js, I believe we should include hls in the dependencies of OvenPlayer, instead of requesting people to add Hls to their dependencies.

BTW i also fixed readme.md doc to use vue template so it's not showing errors in IDE, and demo html that uses dist/ovenplayer.js, so contributors can easliy test their code before pull it.

### CODE REVIEW

**Comment by dygy** [comment]
@SangwonOh let's discuss 😺

**Comment by SangwonOh** [comment]
@dygy Hi. First of all, thank you for your contribution.
If hls is included in the dependency, will there be any problems using it in an HTML environment as shown below?
https://airensoft.gitbook.io/ovenplayer/#initialize-for-hls

**Comment by dygy** [comment]
> @dygy Hi. First of all, thank you for your contribution. If hls is included in the dependency, will there be any problems using it in an HTML environment as shown below? https://airensoft.gitbook.io/ovenplayer/#initialize-for-hls

there will be no problem. People will just be free to not do it. So HLS support will be native, and none of the actions will be required from the developers. And what is good too - is that ovenplayer will control HLS behaviour. Because currently, people are just downloading the latest HLS.js due to documentation, so if the latest version of HL
S js will not work for handlers that oven player expects - people will have broken his players.
Screenshot 2023-10-13 at 11 38 13
regarding the section in docs, we will just not ask people to input this tag, they will not need it anymore.

**Comment by SangwonOh** [comment]
All right. Thanks. Please give me some time to think about it so I can fully understand the pros and cons.

**Comment by SangwonOh** [comment]
@dygy Can you resolve the conflict and commit again? I also want to test it. Thanks!

**Comment by dygy** [comment]
@SangwonOh 
way of testing:
Screenshot 2023-10-20 at 12 13 32

test cases:
1. safari loads HLS stream ✅ 
2. safari unloads HLS stream and checks the network that the HLS stream stopped at the networks ✅ 
3. chrome load HLS stream ✅ 
4. chrome unloads the HLS stream, and checks the network that the HLS stream stopped at the networks ✅ 
5. chrome check auto mute HLS stream ✅ 
6. chrome check mute/unmute ✅ 
7. chrome check change quality ✅ 
8. chrome check change source ✅ 
9. safari check mute/unmute ✅ 

anything else?

**Comment by SangwonOh** [comment]
@dygy Hi. Everything of your work working great!

But I don't think it's a good idea to include hlsjs code in ovenplayer code.

First, the size of the ovenplayer.js file and ovenplayer.js.map file increases by nearly twice. This may not be a big problem and can be solved with a bundler.
The second biggest problem is that users cannot specify the version of hls.js. Newer versions of hls.js may have regression bugs. Also, some users may prefer the version of hls.js that they are using stably.

So, I think it is correct for the user to add hls.js at the application level.




> As a user of OvenPlayer, I had to use OvenPlayer with HLS. There are mentions that Ovenplayers asks for HLS js, but how it uses it isn't nice.

My guess, The reason you wanted to include hls.js in ovenplayer was probably because of poor usability when using ovenplayer with hls.js in an ES6 environment.

We have to go through the trouble of importing Hls with `import Hls from "hls.js"` and putting it in the window scope like `window.Hls= Hls`. 

This inconvenience will create difficulties when creating vue and react components.

So, I thought about making it possible to specify the Hls to be used when initializing the player. Something like this.

```javascript
Import Hls from 'hls'

OvenPlayer.create('player', {
    autoStart: true,
    sources: [
        {
            type: 'hls',
            file: 'https://xxxx.xxxx.xxx/xxx.m3u8'
        },
    ],
    hlsContext: Hls,
    hlsConfig: {
        "debug": false,
        "lowLatencyMode": false
    }
});
```

How do you think? 😎

**Comment by dygy** [comment]
> @dygy Hi. Everything of your work working great!
> 
> But I don't think it's a good idea to include hlsjs code in ovenplayer code.
> 
> First, the size of the ovenplayer.js file and ovenplayer.js.map file increases by nearly twice. This may not be a big problem and can be solved with a bundler.
> The second biggest problem is that users cannot specify the version of hls.js. Newer versions of hls.js may have regression bugs. Also, some users may prefer the version of hls.js that they are using stably.
> 
> So, I think it is correct for the user to add hls.js at the application level.
> 
> 
> 
> 
> > As a user of OvenPlayer, I had to use OvenPlayer with HLS. There are mentions that Ovenplayers asks for HLS js, but how it uses it isn't nice.
> 
> My guess, The reason you wanted to include hls.js in ovenplayer was probably because of poor usability when using ovenplayer with hls.js in an ES6 environment.
> 
> We have to go through the trouble of importing Hls with `import Hls from "hls.js"` and putting it in the window scope like `window.Hls= Hls`. 
> 
> This inconvenience will create difficulties when creating vue and react components.
> 
> So, I thought about making it possible to specify the Hls to be used when initializing the player. Something like this.
> 
> ```javascript
> Import Hls from 'hls'
> 
> OvenPlayer.create('player', {
>     autoStart: true,
>     sources: [
>         {
>             type: 'hls',
>             file: 'https://xxxx.xxxx.xxx/xxx.m3u8'
>         },
>     ],
>     hlsContext: Hls,
>     hlsConfig: {
>         "debug": false,
>         "lowLatencyMode": false
>     }
> });
> ```
> 
> How do you think? 😎

Hi. It's a good Idea. But I also think that
New dev-users (including me) don't know what is a stable version of hls js for ovenplayer. So maybe at least we should put an information about it in documentation (because now we have "latest")

**Comment by dygy** [comment]
@SangwonOh i understand the values and will close PR, but let's continue the discussion to understand. Could you please tell me which version of HLS is stable for the open player? Can we add it to docs instead of "latest" flag?

**Comment by SangwonOh** [comment]
@dygy Hi!!

It is difficult to specify a stable hlsjs version. Usually there is no problem with continuing to update to the latest hlsjs.

However, sometimes, for example, when hlsjs makes a patch to improve the logic that synchronizes audio and video, there are rare cases where the A/V sync is out of sync due to poor compatibility with the encoder on the transmitting side. There are many cases to consider because we have to think about the part where the stream is transmitted.

In most cases, I think it is best to use the latest hlsjs during the application development stage. If all tests are performed and it works well, fixing and using the hlsjs version at that point is a way to maintain the application stably.

If there is an issue where the latest hlsjs does not work well during the development stage, it would be good to maintain a good ecosystem by reporting it to our community or the hlsjs community.

**Pull request closed without merging**
