### PR TITLE
fix: prevent vue3 component reload too frequently

### PR DESCRIPTION
**Pull request by miaulightouch**
It fixed component recreate itself too frequently, only reload player when config changed.

### CODE REVIEW

**Comment by SangwonOh** [comment]
@miaulightouch Hi. Thanks
For publishing to npm, Do i need to update `packages/vue3/dist` directory?

**Comment by SangwonOh** [comment]
@miaulightouch Hi. again! 
I'm going to publish your implementation to npm. Do I need run cmd before publish it?

**Comment by miaulightouch** [comment]
> @miaulightouch Hi. again! I'm going to publish your implementation to npm. Do I need run cmd before publish it?

build required.

**Comment by SangwonOh** [comment]
Thanks!

**Pull request merged**
